### ISSUE TITLE
Retire HTTP API as datasource for cvexplore

### ISSUE THREAD

**Issue by P-T-I** [cve-search/CveXplore#222]
Open question; is the HTTP API as a datasource still needed or can we retire this funcitonality in light of the #213 roadmap

**Comment by baonq-me** [comment]
What do you mean by "retire"?

**Comment by P-T-I** [comment]
Remove... CveXplore is able to use the cvesearch query api endpoint as a datasource; but for me (looking at the new design) this is no longer a viable option as it feels like going in circles...

**Comment by baonq-me** [comment]
> Remove... CveXplore is able to use the cvesearch query api endpoint as a datasource; but for me (looking at the new design) this is no longer a viable option as it feels like going in circles...

@P-T-I What do you think about my below idea?

Based on [what I have analyzed previously about three use cases](https://github.com/cve-search/CveXplore/issues/212#issuecomment-1854266689):

For the first group of people who want to use CLI. I know many CLI tools use this approach. We can host a public demp instance of `cve-search-api` so people don't need to deploy anything except `CveXplore` (or they can deploy their own instance otherwise if needed).

<img width="600" alt="CleanShot 2023-12-16 at 16 35 24@2x" src="https://github.com/cve-search/CveXplore/assets/1851037/541c2c8a-449a-442b-a802-325ab51acf85">

For the second group of people who want to use every component:

<img width="588" alt="CleanShot 2023-12-16 at 16 40 33@2x" src="https://github.com/cve-search/CveXplore/assets/1851037/49d7daa1-2268-4d71-a78c-0e963f86a56e">

For the third group of people who care about integrations rather than GUI:

<img width="589" alt="CleanShot 2023-12-16 at 16 41 59@2x" src="https://github.com/cve-search/CveXplore/assets/1851037/e433854c-77df-4389-a53c-04ce1d8b2d0b">

Another thing to consider is that 'cve-search`  is currently having 2.1K stars, so people will likely want to contribute to that project more than a new and fewer stars project. Of course, we can split `cve-search` into two seperate folders, for example, `cve-search-frontend` and `cve-search-api`.

**Comment by P-T-I** [comment]
@baonq-me FYI there is a public instance (https://cvepremium.circl.lu) and yes, the first use case you described is exactly where I designed cvexplore for; for people who just want to download the lib and use the public instance as a data source. So I think we can agree that we'll keep that as is.

I don't believe splitting up the CveSearch rest api from the frontend source code would lead to much benefit. So only the CLI functionality would be fased out (in due time) from the CveSearch repo.

**Comment by P-T-I** [comment]
I believe this issue can be closed; feel free to reopen if needed!
